# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    sources.google.com/release: devel
    duck.knative.dev/source: "true"
    sources.google.com/crd-install: "true"
  annotations:
    registry.knative.dev/eventTypes: |
      [
        { "type": "google.com.mongodb.collection.v1.inserted", "description": "Sent when a new object is successfully created in a given collection. A failed upload does not trigger this event."  },
        { "type": "google.com.mongodb.collection.v1.deleted", "description": "Sent when an object has been permanently deleted from a collection. A failed deletion does not trigger this event."},
        { "type": "google.com.mongodb.collection.v1.updated", "description": "Sent when an existing object is successfully updated in a given collection. This includes only rewriting an existing object. A failed update does not trigger this event."  },
      ]
  name: mongodbsources.sources.google.com
spec:
  group: sources.google.com
  names:
    categories:
      - all
      - knative
      - sources
    kind: MongoDbSource
    plural: mongodbsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
