/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/googleinterns/knative-source-mongodb/pkg/apis/sources/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MongoDbSourceLister helps list MongoDbSources.
type MongoDbSourceLister interface {
	// List lists all MongoDbSources in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.MongoDbSource, err error)
	// MongoDbSources returns an object that can list and get MongoDbSources.
	MongoDbSources(namespace string) MongoDbSourceNamespaceLister
	MongoDbSourceListerExpansion
}

// mongoDbSourceLister implements the MongoDbSourceLister interface.
type mongoDbSourceLister struct {
	indexer cache.Indexer
}

// NewMongoDbSourceLister returns a new MongoDbSourceLister.
func NewMongoDbSourceLister(indexer cache.Indexer) MongoDbSourceLister {
	return &mongoDbSourceLister{indexer: indexer}
}

// List lists all MongoDbSources in the indexer.
func (s *mongoDbSourceLister) List(selector labels.Selector) (ret []*v1alpha1.MongoDbSource, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MongoDbSource))
	})
	return ret, err
}

// MongoDbSources returns an object that can list and get MongoDbSources.
func (s *mongoDbSourceLister) MongoDbSources(namespace string) MongoDbSourceNamespaceLister {
	return mongoDbSourceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MongoDbSourceNamespaceLister helps list and get MongoDbSources.
type MongoDbSourceNamespaceLister interface {
	// List lists all MongoDbSources in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.MongoDbSource, err error)
	// Get retrieves the MongoDbSource from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.MongoDbSource, error)
	MongoDbSourceNamespaceListerExpansion
}

// mongoDbSourceNamespaceLister implements the MongoDbSourceNamespaceLister
// interface.
type mongoDbSourceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MongoDbSources in the indexer for a given namespace.
func (s mongoDbSourceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MongoDbSource, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MongoDbSource))
	})
	return ret, err
}

// Get retrieves the MongoDbSource from the indexer for a given namespace and name.
func (s mongoDbSourceNamespaceLister) Get(name string) (*v1alpha1.MongoDbSource, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("mongodbsource"), name)
	}
	return obj.(*v1alpha1.MongoDbSource), nil
}
