dist: bionic
git:
  depth: 3
language: go
go:
  - 1.14.x
before_script:
  - go get golang.org/x/lint/golint
script:
  - test -z "$(gofmt -s -l cmd/ pkg/)" || (echo "formatting failed. run `gofmt -s -w cmd/ pkg/` to fix." && exit 1)
  - golint -set_exit_status cmd/... pkg/...
  - go test -v ./cmd/... ./pkg/...
env:
  - GO111MODULE=on
install: true
