dist: bionic
git:
  depth: 3
language: go
go:
  - 1.14.x
before_script:
  - go get golang.org/x/lint/golint
script:
  - gofmt -d -e -l -s cmd/ pkg/
  - golint -set_exit_status cmd/... pkg/...
  - go test -v ./...
