/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/googleinterns/knative-source-mongodb/pkg/apis/sources/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMongoDbSources implements MongoDbSourceInterface
type FakeMongoDbSources struct {
	Fake *FakeSourcesV1alpha1
	ns   string
}

var mongodbsourcesResource = schema.GroupVersionResource{Group: "sources", Version: "v1alpha1", Resource: "mongodbsources"}

var mongodbsourcesKind = schema.GroupVersionKind{Group: "sources", Version: "v1alpha1", Kind: "MongoDbSource"}

// Get takes name of the mongoDbSource, and returns the corresponding mongoDbSource object, and an error if there is any.
func (c *FakeMongoDbSources) Get(name string, options v1.GetOptions) (result *v1alpha1.MongoDbSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mongodbsourcesResource, c.ns, name), &v1alpha1.MongoDbSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongoDbSource), err
}

// List takes label and field selectors, and returns the list of MongoDbSources that match those selectors.
func (c *FakeMongoDbSources) List(opts v1.ListOptions) (result *v1alpha1.MongoDbSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mongodbsourcesResource, mongodbsourcesKind, c.ns, opts), &v1alpha1.MongoDbSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MongoDbSourceList{ListMeta: obj.(*v1alpha1.MongoDbSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.MongoDbSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mongoDbSources.
func (c *FakeMongoDbSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mongodbsourcesResource, c.ns, opts))

}

// Create takes the representation of a mongoDbSource and creates it.  Returns the server's representation of the mongoDbSource, and an error, if there is any.
func (c *FakeMongoDbSources) Create(mongoDbSource *v1alpha1.MongoDbSource) (result *v1alpha1.MongoDbSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mongodbsourcesResource, c.ns, mongoDbSource), &v1alpha1.MongoDbSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongoDbSource), err
}

// Update takes the representation of a mongoDbSource and updates it. Returns the server's representation of the mongoDbSource, and an error, if there is any.
func (c *FakeMongoDbSources) Update(mongoDbSource *v1alpha1.MongoDbSource) (result *v1alpha1.MongoDbSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mongodbsourcesResource, c.ns, mongoDbSource), &v1alpha1.MongoDbSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongoDbSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMongoDbSources) UpdateStatus(mongoDbSource *v1alpha1.MongoDbSource) (*v1alpha1.MongoDbSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mongodbsourcesResource, "status", c.ns, mongoDbSource), &v1alpha1.MongoDbSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongoDbSource), err
}

// Delete takes name of the mongoDbSource and deletes it. Returns an error if one occurs.
func (c *FakeMongoDbSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mongodbsourcesResource, c.ns, name), &v1alpha1.MongoDbSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMongoDbSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mongodbsourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MongoDbSourceList{})
	return err
}

// Patch applies the patch and returns the patched mongoDbSource.
func (c *FakeMongoDbSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MongoDbSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mongodbsourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MongoDbSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MongoDbSource), err
}
